### ISSUE TITLE
Galaxy config to work with JCaaS

### ISSUE THREAD

**Issue by ieguinoa** [usegalaxy-eu/sorting-hat#1]
Hi all,

I was wondering if you could please guide me on how to configure Galaxy to make use of jcaas? Setting up the service itself is clear but I'm a bit lost on how to make Galaxy do the POST request to it and use the output to submit the job. 

Thanks! 
Ignacio

**Comment by ieguinoa** [comment]
Thanks Helena for the reply. Of course there is no hurry here, I'm deploying a new server now and will definitely make use of this in the future but it's not the priority now. 
I will be waiting for it and if you can comment, as you said, how will this project co-evolve with the newest Galaxy version(s) so I can catch up then that would be great. 
I will be experimenting a bit with this too and hope I can also make some contributions to the project.

Thanks again for the help!
Ignacio

**Comment by bgruening** [comment]
@ieguinoa we will discuss the future of JCaaS internally. Maybe we abandon it and integrate all this into core Galaxy with the new upcoming 18.09. Whatever we decide we will let you know.

**Comment by abretaud** [comment]
Hi! So in 2021 is this repo still a good way to go or not? (Thinking about it for usegalaxy.fr)

**Comment by gmauro** [comment]
We are currently using it for EU.

**Comment by bgruening** [comment]
And we are planning to use it :) @gmauro put recently some effort into adding test-coverage to this code as well.

**Comment by abretaud** [comment]
Ok, good to know, thanks! I'll have a look at it
